In [1]:
import swift_app as swift
import pandas as pd
import glob

In [13]:
import importlib
import swift_app.api as _api
importlib.reload(_api)
importlib.reload(swift)

In [ ]:
swift.merge(input_dir="output", datasets=["discharge"], output_dir='/home/saratchandra_ch/Documents')

In [ ]:
swift.wris.download(
    basin=6,
    variable=["solar", "sediment"],
    start_date="2024-01-01",
    overwrite=True,
    merge=True,
    plot=True,
    output_dir="data"
)

In [ ]:
dir(swift)

In [ ]:
swift.datasets.discharge

In [ ]:
swift.wris.download(
    basin="Krishna",
    variable=["solar", "discharge"],
    overwrite=True,
    merge=True,
    plot=True
)

In [1]:
import swift_app as swift

In [2]:
swift.basins()

SWIFT Table
Rows: 17 | Columns: 2
----------------------------------------
    id                                              basin
0    1                              Brahmani and Baitarni
1    2                                            Cauvery
2    3    East flowing rivers between Mahanadi and Pennar
3    4  East flowing rivers between Pennar and Kanyaku...
4    5                                           Godavari
5    6                                            Krishna
6    7                                           Mahanadi
7    8                                               Mahi
8    9  Minor rivers draining into Myanmar and Bangladesh
9   10                                            Narmada
10  11                                             Pennar
11  12                                          Sabarmati
12  13                                       Subernarekha
13  14                                               Tapi
14  15      West flowing rivers from Tadri to Kanyakumari
15  16             West flowing rivers from Tapi to Tadri
16  17  West flowing rivers of Kutch and Saurashtra in...

In [3]:
stations = swift.wris.stations("Godavari")

In [5]:
stations

,station_code,station_name,latitude,longitude,river
0,001-lgdhyd,Somanpally(Seasonal),18.6167,79.8000,Maner
1,007-ugdhyd,Pachegaon,19.5353,74.8336,Pravara
2,008-ugdhyd,Lasur,19.9375,74.0250,Shivna
3,013-UGDHYD,Zari,19.3947,76.7733,Purna
4,019-lgdhyd,Sangam (Murredu),17.5936,80.8217,Murredu
5,020-ugdhyd,Degloor,18.5456,77.5775,Manjira
6,021-UGDHYD,Betmogra,18.7122,77.5250,Maner
7,021-lgdhyd,Potteru (Potteruvagu),18.1894,81.7981,Sabari
8,024-UGDHYD,Gandlapet,18.8211,78.4381,Peddavagu
9,029-LGDHYD,VALAMURU (Pamuleru),17.6331,81.6361,Pamuleru
10,030-UGDHYD,JANNEPALLY,18.8136,78.0633,Poolanvagu
11,032-LGDHYD,Atreyapuram (Gauthami),16.8150,81.8164,Gowthami
12,032-ugdhyd,Pratappur,19.5194,74.3828,Pravara
13,035-LGDHYD,Kothapalle (Sileru),17.8253,81.5528,Sileru
14,036-lgdhyd,Ankushapur,16.3528,79.6381,Maner
15,040-lgdhyd,Jeeraguda,18.9492,82.4061,Kalab
16,041-lgdhyd,Sirimoda,18.6203,82.8717,Kalab
17,042-LGDHYD,Kunturla (Machkund),18.1992,82.6497,Machkund
18,043-LGDHYD,ALLAM VARI GHANAPUR,18.3378,80.4300,Peddavagu
19,44-LGDHYD,GARIMILLAPALLI,18.4469,79.7047,Maner
20,ANK001,ANKUSHAPUR,18.3528,79.6381,Maner
21,AVG001,ALLAM VARI GHANAPUr,18.3861,80.3928,Peddavagu
22,Anantwadi,Anantwadi,19.8461,77.8672,Adhala
23,Arni,Arni,20.0619,77.9486,Adhala
24,BUTARAM,BUTARAM,18.3533,80.4078,Lakhnavaram Vagu
25,Bhamragad,Bhamragad,19.4164,80.5861,Watiganga
26,CW1WAR000054,Nagari,20.4256,78.8744,Wunna
27,Dommeru,Kovvada Kalva near dommeru,17.0181,81.6644,Kovvadakalva
28,GRM001,GARIMILLAPALLi,18.4469,79.7047,Maner
29,Hamdapur,Hamdapur,20.6806,78.8511,Wunna
30,KAMARAJUPETA,KAMARAJUPETA,17.3072,81.9153,Burada Kalva
31,Khadka,Khadka,19.9103,78.1853,Adhala
32,KoliBk,Koli(BK),20.0414,78.1667,Adhala
33,MANGAPET,MANGAPET,18.2717,80.5283,Gowrarapuvagu
34,Murli,Murli,19.4681,77.9861,Adhala
35,NAG001,NAGARAM,18.2892,79.4739,Maner
36,PEDAGEDDADA,PEDAGEDDADA,17.4692,81.7342,Seethapalli Vagu
37,Pipriya,Pipriya,21.3408,80.5547,Wainganga
38,Pragadapalli,Kovvadakalva Pragadapalli,17.2139,81.5967,Kovvadakalva
39,SEETHAPALLI,SEETHAPALLI,17.3969,81.7864,Seethapalli Vagu
40,Sharad,Sharad,19.9700,78.3353,Adhala
41,Takali,Takali,19.8442,78.6008,Adhala

In [6]:
cwc = swift.cwc.stations()

In [7]:
cwc

SWIFT Table
Rows: 1,997 | Columns: 2
----------------------------------------
             code                    name
0               -                       -
1              --                       -
2     01BR01BW001             01BR01BW001
3     01BR01BW002             01BR01BW002
4     01BR01BW005             01BR01BW005
...           ...                     ...
1992  WBSWIDCTD26  4no mansha mini market
1993       WQ-225            Abhalvad dam
1994       WQ-312                 Aambala
1995       WQ-378       aamli chharchhota
1996       WQ-382                  abhlod

[1997 rows x 2 columns]

In [18]:
station_id = cwc.iloc[0]["code"] if len(cwc) else "GDA001"
meta = swift.cwc.stations(station=station_id)

Warning: live CWC station refresh failed; using cached/packaged station table.
Fetching CWC station metadata from API

In [19]:
meta

SWIFT Table
Rows: 1 | Columns: 2
----------------------------------------
         code           name
1  038-CDJAPR  Kalisindh Dam